apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: account-service
  name: account-service
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: account-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/test: "true"
        io.kompose.service: account-service
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_PASSWORD
          value: "123456"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgresql:5432/pipe
        - name: SPRING_DATASOURCE_USERNAME
          value: pipe
        image: sansanvn/hellorepo:account-service
        name: account-service
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
