apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQUlYQk9RNFBSRVRXVElaQUE= #echo -n 'xxx' | base64
  AWS_ACCESS_SECRET: NVc2ckd2ZkpUaklqOTZ5V0NOY0hNUlRkT3RBakQ5TnVlU3IwL1VtRg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapicms-service
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: strapicms-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: strapicms-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/test: "true"
        io.kompose.service: strapicms-service
    spec:     # pod spec                  
      containers: 
      - env:
        - name: DATABASE_HOST
          value: "mongo"
        - name: DATABASE_PORT
          value: "27017"
        - name: DATABASE_NAME
          value: "ppcms"
        - name: DATABASE_USERNAME
          value: "root"
        - name: DATABASE_PASSWORD
          value: "root"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_SECRET
        name: strapicms-service
        image: sansanvn/hellorepo:strapicms-service
        imagePullPolicy: Always
        ports:
        - containerPort: 1337
      restartPolicy: Always
      serviceAccountName: ""
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
    konghq.com/plugins: rl-by-ip
  labels:
    io.kompose.service: strapicms-service
  name: strapicms-service
spec:
  ports:
  - name: "1337"
    port: 1337
    targetPort: 1337
    nodePort: 30010
  selector:
    io.kompose.service: strapicms-service
  type: NodePort
status:
  loadBalancer: {}
