apiVersion: configuration.konghq.com/v1
kind: KongPlugin #The KongPlugin resource only needs to be defined once and can be applied to any Service, Consumer, or Route in the namespace. If you want the plugin to be available cluster-wide, create the resource as a KongClusterPlugin instead of KongPlugin.
metadata:
  name: cors-plugin
config: 
  origins:
  - "*"
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  headers:
  - Accept
  - Accept-Version
  - Content-Length
  - Content-MD5
  - Content-Type
  - Date
  - X-Auth-Token
  exposed_headers:
  #- X-Auth-Token
  credentials: true
  max_age: 3600
plugin: cors
