apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
    konghq.com/plugins: rl-by-ip
  creationTimestamp: null
  labels:
    io.kompose.service: account-service
  name: account-service
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 8080
    nodePort: 30000
  selector:
    io.kompose.service: account-service
  type: NodePort
status:
  loadBalancer: {}
