apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cart-service
  name: cart-service
spec:
  ports:
  - name: "9001"
    port: 9001
    targetPort: 8080
  selector:
    io.kompose.service: cart-service
  type: NodePort
status:
  loadBalancer: {}
