- hosts: kmaster
  become: yes
  tasks:
    - name: Ansible delete file example
      become: yes
      become_user: sontm
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - $HOME/cluster_initialized.txt
        - $HOME/pod_network_setup.txt

    - name: clean up kubeadm
      become: yes
      become_user: sontm
      shell: "sudo kubeadm reset --force"

    - name: initialize the cluster
      become: yes
      become_user: sontm
      shell: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: sontm
      file:
        path: /home/sontm/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/sontm/.kube/config
        remote_src: yes
        owner: sontm

    - name: install Pod network
      become: yes
      become_user: sontm
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt