{
 "title": "Linux metrics (CPU, memory)",
 "description": "6.2 Grafana",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "AdhocFilters", "label": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Topk cpu usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "topk(10, cpu_usage)", "legendFormat": "{{process}} {{pid}}" }
   ]
  },
  {
   "title": "Memory_usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "topk(10,memory_usage)", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "Average CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "targets": [
    { "expr": "avg(cpu_usage)", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "CPU Overall",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 8 },
   "targets": [
    { "expr": "sum(cpu_usage)", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "Memory_usage instant",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 8 },
   "targets": [
    { "expr": "avg(memory_usage)", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "cpu usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "topk(10, cpu_usage)", "legendFormat": "{{process}} {{pid}}" }
   ]
  }
 ]
}